<?php

return array(

	'country_regions' => array(
		array('name' => 'Afghanistan', 'code_3_digit' => 'AFG', 'code_2_digit' => 'AF'),
		array('name' => 'Albania', 'code_3_digit' => 'ALB', 'code_2_digit' => 'AL'),
		array('name' => 'Algeria', 'code_3_digit' => 'DZA', 'code_2_digit' => 'DZ'),
		array('name' => 'American Samoa', 'code_3_digit' => 'ASM', 'code_2_digit' => 'AS'),
		array('name' => 'Andorra', 'code_3_digit' => 'AND', 'code_2_digit' => 'AD'),
		array('name' => 'Angola', 'code_3_digit' => 'AGO', 'code_2_digit' => 'AO'),
		array('name' => 'Anguilla', 'code_3_digit' => 'AIA', 'code_2_digit' => 'AI'),
		array('name' => 'Antarctica', 'code_3_digit' => 'ATA', 'code_2_digit' => 'AQ'),
		array('name' => 'Antigua and Barbuda', 'code_3_digit' => 'ATG', 'code_2_digit' => 'AG'),
		array('name' => 'Argentina', 'code_3_digit' => 'ARG', 'code_2_digit' => 'AR'),
		array('name' => 'Armenia', 'code_3_digit' => 'ARM', 'code_2_digit' => 'AM'),
		array('name' => 'Aruba', 'code_3_digit' => 'ABW', 'code_2_digit' => 'AW'),
		array('name' => 'Australia', 'code_3_digit' => 'AUS', 'code_2_digit' => 'AU'),
		array('name' => 'Austria', 'code_3_digit' => 'AUT', 'code_2_digit' => 'AT'),
		array('name' => 'Azerbaijan', 'code_3_digit' => 'AZE', 'code_2_digit' => 'AZ'),
		array('name' => 'Bahamas', 'code_3_digit' => 'BHS', 'code_2_digit' => 'BS'),
		array('name' => 'Bahrain', 'code_3_digit' => 'BHR', 'code_2_digit' => 'BH'),
		array('name' => 'Bangladesh', 'code_3_digit' => 'BGD', 'code_2_digit' => 'BD'),
		array('name' => 'Barbados', 'code_3_digit' => 'BRB', 'code_2_digit' => 'BB'),
		array('name' => 'Belarus', 'code_3_digit' => 'BLR', 'code_2_digit' => 'BY'),
		array('name' => 'Belgium', 'code_3_digit' => 'BEL', 'code_2_digit' => 'BE'),
		array('name' => 'Belize', 'code_3_digit' => 'BLZ', 'code_2_digit' => 'BZ'),
		array('name' => 'Benin', 'code_3_digit' => 'BEN', 'code_2_digit' => 'BJ'),
		array('name' => 'Bermuda', 'code_3_digit' => 'BMU', 'code_2_digit' => 'BM'),
		array('name' => 'Bhutan', 'code_3_digit' => 'BTN', 'code_2_digit' => 'BT'),
		array('name' => 'Bolivia', 'code_3_digit' => 'BOL', 'code_2_digit' => 'BO'),
		array('name' => 'Bosnia-Herzegovina', 'code_3_digit' => 'BIH', 'code_2_digit' => 'BA'),
		array('name' => 'Botswana', 'code_3_digit' => 'BWA', 'code_2_digit' => 'BW'),
		array('name' => 'Bouvet Island', 'code_3_digit' => 'BVT', 'code_2_digit' => 'BV'),
		array('name' => 'Brazil', 'code_3_digit' => 'BRA', 'code_2_digit' => 'BR'),
		array('name' => 'British Indian Ocean Territory', 'code_3_digit' => 'IOT', 'code_2_digit' => 'IO'),
		array('name' => 'Brunei Darussalam', 'code_3_digit' => 'BRN', 'code_2_digit' => 'BN'),
		array('name' => 'Bulgaria', 'code_3_digit' => 'BGR', 'code_2_digit' => 'BG'),
		array('name' => 'Burkina Faso', 'code_3_digit' => 'BFA', 'code_2_digit' => 'BF'),
		array('name' => 'Burundi', 'code_3_digit' => 'BDI', 'code_2_digit' => 'BI'),
		array('name' => 'Cambodia', 'code_3_digit' => 'KHM', 'code_2_digit' => 'KH'),
		array('name' => 'Cameroon', 'code_3_digit' => 'CMR', 'code_2_digit' => 'CM'),
		array('name' => 'Canada', 'code_3_digit' => 'CAN', 'code_2_digit' => 'CA'),
		array('name' => 'Cape Verde', 'code_3_digit' => 'CPV', 'code_2_digit' => 'CV'),
		array('name' => 'Cayman Islands', 'code_3_digit' => 'CYM', 'code_2_digit' => 'KY'),
		array('name' => 'Central African Republic', 'code_3_digit' => 'CAF', 'code_2_digit' => 'CF'),
		array('name' => 'Chad', 'code_3_digit' => 'TCD', 'code_2_digit' => 'TD'),
		array('name' => 'Chile', 'code_3_digit' => 'CHL', 'code_2_digit' => 'CL'),
		array('name' => 'China', 'code_3_digit' => 'CHN', 'code_2_digit' => 'CN'),
		array('name' => 'Christmas Island', 'code_3_digit' => 'CXR', 'code_2_digit' => 'CX'),
		array('name' => 'Cocos (Keeling) Islands', 'code_3_digit' => 'CCK', 'code_2_digit' => 'CC'),
		array('name' => 'Colombia', 'code_3_digit' => 'COL', 'code_2_digit' => 'CO'),
		array('name' => 'Comoros', 'code_3_digit' => 'COM', 'code_2_digit' => 'KM'),
		array('name' => 'Congo', 'code_3_digit' => 'COG', 'code_2_digit' => 'CG'),
		array('name' => 'Congo, Democratic Republic of', 'code_3_digit' => 'COD', 'code_2_digit' => 'CD'),
		array('name' => 'Cook Islands', 'code_3_digit' => 'COK', 'code_2_digit' => 'CK'),
		array('name' => 'Costa Rica', 'code_3_digit' => 'CRI', 'code_2_digit' => 'CR'),
		array('name' => 'Cote D\'Ivoire', 'code_3_digit' => 'CIV', 'code_2_digit' => 'CI'),
		array('name' => 'Croatia (Hrvatska)', 'code_3_digit' => 'HRV', 'code_2_digit' => 'HR'),
		array('name' => 'Cuba', 'code_3_digit' => 'CUB', 'code_2_digit' => 'CU'),
		array('name' => 'Cyprus', 'code_3_digit' => 'CYP', 'code_2_digit' => 'CY'),
		array('name' => 'Czech Republic', 'code_3_digit' => 'CZE', 'code_2_digit' => 'CZ'),
		array('name' => 'Denmark', 'code_3_digit' => 'DNK', 'code_2_digit' => 'DK'),
		array('name' => 'Djibouti', 'code_3_digit' => 'DJI', 'code_2_digit' => 'DJ'),
		array('name' => 'Dominica', 'code_3_digit' => 'DMA', 'code_2_digit' => 'DM'),
		array('name' => 'Dominican Republic', 'code_3_digit' => 'DOM', 'code_2_digit' => 'DO'),
		array('name' => 'East Timor', 'code_3_digit' => 'TMP', 'code_2_digit' => 'TP'),
		array('name' => 'Ecuador', 'code_3_digit' => 'ECU', 'code_2_digit' => 'EC'),
		array('name' => 'Egypt', 'code_3_digit' => 'EGY', 'code_2_digit' => 'EG'),
		array('name' => 'El Salvador', 'code_3_digit' => 'SLV', 'code_2_digit' => 'SV'),
		array('name' => 'Equatorial Guinea', 'code_3_digit' => 'GNQ', 'code_2_digit' => 'GQ'),
		array('name' => 'Eritrea', 'code_3_digit' => 'ERI', 'code_2_digit' => 'ER'),
		array('name' => 'Estonia', 'code_3_digit' => 'EST', 'code_2_digit' => 'EE'),
		array('name' => 'Ethiopia', 'code_3_digit' => 'ETH', 'code_2_digit' => 'ET'),
		array('name' => 'Falkland Islands (Malvinas)', 'code_3_digit' => 'FLK', 'code_2_digit' => 'FK'),
		array('name' => 'Faroe Islands', 'code_3_digit' => 'FRO', 'code_2_digit' => 'FO'),
		array('name' => 'Fiji', 'code_3_digit' => 'FJI', 'code_2_digit' => 'FJ'),
		array('name' => 'Finland', 'code_3_digit' => 'FIN', 'code_2_digit' => 'FI'),
		array('name' => 'France', 'code_3_digit' => 'FRA', 'code_2_digit' => 'FR'),
		array('name' => 'French Guiana', 'code_3_digit' => 'GUF', 'code_2_digit' => 'GF'),
		array('name' => 'French Polynesia', 'code_3_digit' => 'PYF', 'code_2_digit' => 'PF'),
		array('name' => 'French Southern Territories', 'code_3_digit' => 'ATF', 'code_2_digit' => 'TF'),
		array('name' => 'Gabon', 'code_3_digit' => 'GAB', 'code_2_digit' => 'GA'),
		array('name' => 'Gambia', 'code_3_digit' => 'GMB', 'code_2_digit' => 'GM'),
		array('name' => 'Georgia', 'code_3_digit' => 'GEO', 'code_2_digit' => 'GE'),
		array('name' => 'Germany', 'code_3_digit' => 'DEU', 'code_2_digit' => 'DE'),
		array('name' => 'Ghana', 'code_3_digit' => 'GHA', 'code_2_digit' => 'GH'),
		array('name' => 'Gibraltar', 'code_3_digit' => 'GIB', 'code_2_digit' => 'GI'),
		array('name' => 'Great Britain (England, Scotland, Wales)', 'code_3_digit' => 'GBR', 'code_2_digit' => 'GB'),
		array('name' => 'Greece', 'code_3_digit' => 'GRC', 'code_2_digit' => 'GR'),
		array('name' => 'Greenland', 'code_3_digit' => 'GRL', 'code_2_digit' => 'GL'),
		array('name' => 'Grenada', 'code_3_digit' => 'GRD', 'code_2_digit' => 'GD'),
		array('name' => 'Guadeloupe', 'code_3_digit' => 'GLP', 'code_2_digit' => 'GP'),
		array('name' => 'Guam', 'code_3_digit' => 'GUM', 'code_2_digit' => 'GU'),
		array('name' => 'Guatemala', 'code_3_digit' => 'GTM', 'code_2_digit' => 'GT'),
		array('name' => 'Guinea', 'code_3_digit' => 'GIN', 'code_2_digit' => 'GN'),
		array('name' => 'Guinea-Bissau', 'code_3_digit' => 'GNB', 'code_2_digit' => 'GW'),
		array('name' => 'Guyana', 'code_3_digit' => 'GUY', 'code_2_digit' => 'GY'),
		array('name' => 'Haiti', 'code_3_digit' => 'HTI', 'code_2_digit' => 'HT'),
		array('name' => 'Heard Island and McDonald Islands', 'code_3_digit' => 'HMD', 'code_2_digit' => 'HM'),
		array('name' => 'Honduras', 'code_3_digit' => 'HND', 'code_2_digit' => 'HN'),
		array('name' => 'Hong Kong SAR of PRC', 'code_3_digit' => 'HKG', 'code_2_digit' => 'HK'),
		array('name' => 'Hungary', 'code_3_digit' => 'HUN', 'code_2_digit' => 'HU'),
		array('name' => 'Iceland', 'code_3_digit' => 'ISL', 'code_2_digit' => 'IS'),
		array('name' => 'India', 'code_3_digit' => 'IND', 'code_2_digit' => 'IN'),
		array('name' => 'Indonesia', 'code_3_digit' => 'IDN', 'code_2_digit' => 'ID'),
		array('name' => 'Iran', 'code_3_digit' => 'IRN', 'code_2_digit' => 'IR'),
		array('name' => 'Iraq', 'code_3_digit' => 'IRQ', 'code_2_digit' => 'IQ'),
		array('name' => 'Ireland', 'code_3_digit' => 'IRL', 'code_2_digit' => 'IE'),
		array('name' => 'Israel', 'code_3_digit' => 'ISR', 'code_2_digit' => 'IL'),
		array('name' => 'Italy', 'code_3_digit' => 'ITA', 'code_2_digit' => 'IT'),
		array('name' => 'Jamaica', 'code_3_digit' => 'JAM', 'code_2_digit' => 'JM'),
		array('name' => 'Japan', 'code_3_digit' => 'JPN', 'code_2_digit' => 'JP'),
		array('name' => 'Jordan', 'code_3_digit' => 'JOR', 'code_2_digit' => 'JO'),
		array('name' => 'Kazakhstan', 'code_3_digit' => 'KAZ', 'code_2_digit' => 'KZ'),
		array('name' => 'Kenya', 'code_3_digit' => 'KEN', 'code_2_digit' => 'KE'),
		array('name' => 'Kiribati', 'code_3_digit' => 'KIR', 'code_2_digit' => 'KI'),
		array('name' => 'Republic of Korea (South Korea)', 'code_3_digit' => 'KOR', 'code_2_digit' => 'KR'),
		array('name' => 'Korea, Democratic People\'s Republic (North Korea)', 'code_3_digit' => 'PRK', 'code_2_digit' => 'KP'),
		array('name' => 'Kosovo', 'code_3_digit' => 'UNK', 'code_2_digit' => 'XK'),
		array('name' => 'Kuwait', 'code_3_digit' => 'KWT', 'code_2_digit' => 'KW'),
		array('name' => 'Kyrgyzstan', 'code_3_digit' => 'KGZ', 'code_2_digit' => 'KG'),
		array('name' => 'Lao People\'s Democratic Republic', 'code_3_digit' => 'LAO', 'code_2_digit' => 'LA'),
		array('name' => 'Latvia', 'code_3_digit' => 'LVA', 'code_2_digit' => 'LV'),
		array('name' => 'Lebanon', 'code_3_digit' => 'LBN', 'code_2_digit' => 'LB'),
		array('name' => 'Lesotho', 'code_3_digit' => 'LSO', 'code_2_digit' => 'LS'),
		array('name' => 'Liberia', 'code_3_digit' => 'LBR', 'code_2_digit' => 'LR'),
		array('name' => 'Libyan Arab Jamahiriya', 'code_3_digit' => 'LBY', 'code_2_digit' => 'LY'),
		array('name' => 'Liechtenstein', 'code_3_digit' => 'LIE', 'code_2_digit' => 'LI'),
		array('name' => 'Lithuania', 'code_3_digit' => 'LTU', 'code_2_digit' => 'LT'),
		array('name' => 'Luxembourg', 'code_3_digit' => 'LUX', 'code_2_digit' => 'LU'),
		array('name' => 'Macao SAR of PRC (Macau)', 'code_3_digit' => 'MAC', 'code_2_digit' => 'MO'),
		array('name' => 'Macedonia', 'code_3_digit' => 'MKD', 'code_2_digit' => 'MK'),
		array('name' => 'Madagascar', 'code_3_digit' => 'MDG', 'code_2_digit' => 'MG'),
		array('name' => 'Malawi', 'code_3_digit' => 'MWI', 'code_2_digit' => 'MW'),
		array('name' => 'Malaysia', 'code_3_digit' => 'MYS', 'code_2_digit' => 'MY'),
		array('name' => 'Maldives', 'code_3_digit' => 'MDV', 'code_2_digit' => 'MV'),
		array('name' => 'Mali', 'code_3_digit' => 'MLI', 'code_2_digit' => 'ML'),
		array('name' => 'Malta', 'code_3_digit' => 'MLT', 'code_2_digit' => 'MT'),
		array('name' => 'Marshall Islands', 'code_3_digit' => 'MHL', 'code_2_digit' => 'MH'),
		array('name' => 'Martinique', 'code_3_digit' => 'MTQ', 'code_2_digit' => 'MQ'),
		array('name' => 'Mauritania', 'code_3_digit' => 'MRT', 'code_2_digit' => 'MR'),
		array('name' => 'Mauritius', 'code_3_digit' => 'MUS', 'code_2_digit' => 'MU'),
		array('name' => 'Mayotte', 'code_3_digit' => 'MYT', 'code_2_digit' => 'YT'),
		array('name' => 'Mexico', 'code_3_digit' => 'MEX', 'code_2_digit' => 'MX'),
		array('name' => 'Micronesia, Federated States of', 'code_3_digit' => 'FSM', 'code_2_digit' => 'FM'),
		array('name' => 'Monaco', 'code_3_digit' => 'MCO', 'code_2_digit' => 'MC'),
		array('name' => 'Mongolia', 'code_3_digit' => 'MNG', 'code_2_digit' => 'MN'),
		array('name' => 'Montenegro', 'code_3_digit' => 'MNE', 'code_2_digit' => 'ME'),
		array('name' => 'Montserrat', 'code_3_digit' => 'MSR', 'code_2_digit' => 'MS'),
		array('name' => 'Morocco', 'code_3_digit' => 'MAR', 'code_2_digit' => 'MA'),
		array('name' => 'Mozambique', 'code_3_digit' => 'MOZ', 'code_2_digit' => 'MZ'),
		array('name' => 'Myanmar', 'code_3_digit' => 'MMR', 'code_2_digit' => 'MM'),
		array('name' => 'Namibia', 'code_3_digit' => 'NAM', 'code_2_digit' => 'NA'),
		array('name' => 'Nauru', 'code_3_digit' => 'NRU', 'code_2_digit' => 'NR'),
		array('name' => 'Nepal', 'code_3_digit' => 'NPL', 'code_2_digit' => 'NP'),
		array('name' => 'Netherlands', 'code_3_digit' => 'NLD', 'code_2_digit' => 'NL'),
		array('name' => 'Netherlands Antilles', 'code_3_digit' => 'ANT', 'code_2_digit' => 'AN'),
		array('name' => 'New Caledonia', 'code_3_digit' => 'NCL', 'code_2_digit' => 'NC'),
		array('name' => 'New Zealand', 'code_3_digit' => 'NZL', 'code_2_digit' => 'NZ'),
		array('name' => 'Nicaragua', 'code_3_digit' => 'NIC', 'code_2_digit' => 'NI'),
		array('name' => 'Niger', 'code_3_digit' => 'NER', 'code_2_digit' => 'NE'),
		array('name' => 'Nigeria', 'code_3_digit' => 'NGA', 'code_2_digit' => 'NG'),
		array('name' => 'Niue', 'code_3_digit' => 'NIU', 'code_2_digit' => 'NU'),
		array('name' => 'Norfolk Island', 'code_3_digit' => 'NFK', 'code_2_digit' => 'NF'),
		array('name' => 'Northern Mariana Islands', 'code_3_digit' => 'MNP', 'code_2_digit' => 'MP'),
		array('name' => 'Norway', 'code_3_digit' => 'NOR', 'code_2_digit' => 'NO'),
		array('name' => 'Oman', 'code_3_digit' => 'OMN', 'code_2_digit' => 'OM'),
		array('name' => 'Pakistan', 'code_3_digit' => 'PAK', 'code_2_digit' => 'PK'),
		array('name' => 'Palau', 'code_3_digit' => 'PLW', 'code_2_digit' => 'PW'),
		array('name' => 'Panama', 'code_3_digit' => 'PAN', 'code_2_digit' => 'PA'),
		array('name' => 'Papua New Guinea', 'code_3_digit' => 'PNG', 'code_2_digit' => 'PG'),
		array('name' => 'Paraguay', 'code_3_digit' => 'PRY', 'code_2_digit' => 'PY'),
		array('name' => 'Peru', 'code_3_digit' => 'PER', 'code_2_digit' => 'PE'),
		array('name' => 'Philippines', 'code_3_digit' => 'PHL', 'code_2_digit' => 'PH'),
		array('name' => 'Pitcairn', 'code_3_digit' => 'PCN', 'code_2_digit' => 'PN'),
		array('name' => 'Poland', 'code_3_digit' => 'POL', 'code_2_digit' => 'PL'),
		array('name' => 'Portugal', 'code_3_digit' => 'PRT', 'code_2_digit' => 'PT'),
		array('name' => 'Puerto Rico', 'code_3_digit' => 'PRI', 'code_2_digit' => 'PR'),
		array('name' => 'Qatar', 'code_3_digit' => 'QAT', 'code_2_digit' => 'QA'),
		array('name' => 'Republic of Moldova', 'code_3_digit' => 'MDA', 'code_2_digit' => 'MD'),
		array('name' => 'Reunion', 'code_3_digit' => 'REU', 'code_2_digit' => 'RE'),
		array('name' => 'Romania', 'code_3_digit' => 'ROM', 'code_2_digit' => 'RO'),
		array('name' => 'Russia', 'code_3_digit' => 'RUS', 'code_2_digit' => 'RU'),
		array('name' => 'Rwanda', 'code_3_digit' => 'RWA', 'code_2_digit' => 'RW'),
		array('name' => 'Saint Helena', 'code_3_digit' => 'SHN', 'code_2_digit' => 'SH'),
		array('name' => 'Saint Kitts and Nevis', 'code_3_digit' => 'KNA', 'code_2_digit' => 'KN'),
		array('name' => 'Saint Lucia', 'code_3_digit' => 'LCA', 'code_2_digit' => 'LC'),
		array('name' => 'Saint Pierre and Miquelon', 'code_3_digit' => 'SPM', 'code_2_digit' => 'PM'),
		array('name' => 'Saint Vincent and the Grenadines', 'code_3_digit' => 'VCT', 'code_2_digit' => 'VC'),
		array('name' => 'Samoa', 'code_3_digit' => 'WSM', 'code_2_digit' => 'WS'),
		array('name' => 'San Marino', 'code_3_digit' => 'SMR', 'code_2_digit' => 'SM'),
		array('name' => 'Sao Tome and Principe', 'code_3_digit' => 'STP', 'code_2_digit' => 'ST'),
		array('name' => 'Saudi Arabia', 'code_3_digit' => 'SAU', 'code_2_digit' => 'SA'),
		array('name' => 'Senegal', 'code_3_digit' => 'SEN', 'code_2_digit' => 'SN'),
		array('name' => 'Serbia', 'code_3_digit' => 'SRB', 'code_2_digit' => 'RS'),
		array('name' => 'Seychelles', 'code_3_digit' => 'SYC', 'code_2_digit' => 'SC'),
		array('name' => 'Sierra Leone', 'code_3_digit' => 'SLE', 'code_2_digit' => 'SL'),
		array('name' => 'Singapore', 'code_3_digit' => 'SGP', 'code_2_digit' => 'SG'),
		array('name' => 'Slovakia', 'code_3_digit' => 'SVK', 'code_2_digit' => 'SK'),
		array('name' => 'Slovenia', 'code_3_digit' => 'SVN', 'code_2_digit' => 'SI'),
		array('name' => 'Solomon Islands', 'code_3_digit' => 'SLB', 'code_2_digit' => 'SB'),
		array('name' => 'Somalia', 'code_3_digit' => 'SOM', 'code_2_digit' => 'SO'),
		array('name' => 'South Africa', 'code_3_digit' => 'ZAF', 'code_2_digit' => 'ZA'),
		array('name' => 'South Georgia and South Sandwich Islands', 'code_3_digit' => 'SGS', 'code_2_digit' => 'GS'),
		array('name' => 'Spain', 'code_3_digit' => 'ESP', 'code_2_digit' => 'ES'),
		array('name' => 'Sri Lanka', 'code_3_digit' => 'LKA', 'code_2_digit' => 'LK'),
		array('name' => 'Sudan', 'code_3_digit' => 'SDN', 'code_2_digit' => 'SD'),
		array('name' => 'Suriname', 'code_3_digit' => 'SUR', 'code_2_digit' => 'SR'),
		array('name' => 'Svalbard and Jan Mayen', 'code_3_digit' => 'SJM', 'code_2_digit' => 'SJ'),
		array('name' => 'Swaziland', 'code_3_digit' => 'SWZ', 'code_2_digit' => 'SZ'),
		array('name' => 'Sweden', 'code_3_digit' => 'SWE', 'code_2_digit' => 'SE'),
		array('name' => 'Switzerland', 'code_3_digit' => 'CHE', 'code_2_digit' => 'CH'),
		array('name' => 'Syria', 'code_3_digit' => 'SYR', 'code_2_digit' => 'SY'),
		array('name' => 'Taiwan', 'code_3_digit' => 'TWN', 'code_2_digit' => 'TW'),
		array('name' => 'Tajikistan', 'code_3_digit' => 'TJK', 'code_2_digit' => 'TJ'),
		array('name' => 'Tanzania, United Republic of', 'code_3_digit' => 'TZA', 'code_2_digit' => 'TZ'),
		array('name' => 'Thailand', 'code_3_digit' => 'THA', 'code_2_digit' => 'TH'),
		array('name' => 'Togo', 'code_3_digit' => 'TGO', 'code_2_digit' => 'TG'),
		array('name' => 'Tokelau', 'code_3_digit' => 'TKL', 'code_2_digit' => 'TK'),
		array('name' => 'Tonga', 'code_3_digit' => 'TON', 'code_2_digit' => 'TO'),
		array('name' => 'Trinidad and Tobago', 'code_3_digit' => 'TTE', 'code_2_digit' => 'TT'),
		array('name' => 'Tunisia', 'code_3_digit' => 'TUN', 'code_2_digit' => 'TN'),
		array('name' => 'Turkey', 'code_3_digit' => 'TUR', 'code_2_digit' => 'TR'),
		array('name' => 'Turkmenistan', 'code_3_digit' => 'TKM', 'code_2_digit' => 'TM'),
		array('name' => 'Turks and Caicos Islands', 'code_3_digit' => 'TCA', 'code_2_digit' => 'TC'),
		array('name' => 'Tuvalu', 'code_3_digit' => 'TUV', 'code_2_digit' => 'TV'),
		array('name' => 'Uganda', 'code_3_digit' => 'UGA', 'code_2_digit' => 'UG'),
		array('name' => 'Ukraine', 'code_3_digit' => 'UKR', 'code_2_digit' => 'UA'),
		array('name' => 'United Arab Emirates', 'code_3_digit' => 'ARE', 'code_2_digit' => 'AE'),
		array('name' => 'United States', 'code_3_digit' => 'USA', 'code_2_digit' => 'US'),
		array('name' => 'United States Minor Outlying Islands', 'code_3_digit' => 'UMI', 'code_2_digit' => 'UM'),
		array('name' => 'Uruguay', 'code_3_digit' => 'URY', 'code_2_digit' => 'UY'),
		array('name' => 'Uzbekistan', 'code_3_digit' => 'UZB', 'code_2_digit' => 'UZ'),
		array('name' => 'Vanuatu', 'code_3_digit' => 'VUT', 'code_2_digit' => 'VU'),
		array('name' => 'Vatican City State', 'code_3_digit' => 'VAT', 'code_2_digit' => 'VA'),
		array('name' => 'Venezuela', 'code_3_digit' => 'VEN', 'code_2_digit' => 'VE'),
		array('name' => 'Vietnam', 'code_3_digit' => 'VNM', 'code_2_digit' => 'VN'),
		array('name' => 'Virgin Islands (UK)', 'code_3_digit' => 'VGB', 'code_2_digit' => 'VG'),
		array('name' => 'Virgin Islands (US)', 'code_3_digit' => 'VIR', 'code_2_digit' => 'VI'),
		array('name' => 'Wallis and Futuna', 'code_3_digit' => 'WLF', 'code_2_digit' => 'WF'),
		array('name' => 'Western Sahara', 'code_3_digit' => 'ESH', 'code_2_digit' => 'EH'),
		array('name' => 'Yemen', 'code_3_digit' => 'YEM', 'code_2_digit' => 'YE'),
		array('name' => 'Zambia', 'code_3_digit' => 'ZMB', 'code_2_digit' => 'ZM'),
		array('name' => 'Zimbabwe', 'code_3_digit' => 'ZWE', 'code_2_digit' => 'ZW'),
	),

	'usa_states' => array(
		array('name' => 'Alabama', 'code_2_digit' => 'AL'),
		array('name' => 'Alaska', 'code_2_digit' => 'AK'),
		array('name' => 'Arizona', 'code_2_digit' => 'AZ'),
		array('name' => 'Arkansas', 'code_2_digit' => 'AR'),
		array('name' => 'California', 'code_2_digit' => 'CA'),
		array('name' => 'Colorado', 'code_2_digit' => 'CO'),
		array('name' => 'Connecticut', 'code_2_digit' => 'CT'),
		array('name' => 'Delaware', 'code_2_digit' => 'DE'),
		array('name' => 'District of Columbia', 'code_2_digit' => 'DC'),
		array('name' => 'Florida', 'code_2_digit' => 'FL'),
		array('name' => 'Georgia', 'code_2_digit' => 'GA'),
		array('name' => 'Hawaii', 'code_2_digit' => 'HI'),
		array('name' => 'Idaho', 'code_2_digit' => 'ID'),
		array('name' => 'Illinois', 'code_2_digit' => 'IL'),
		array('name' => 'Indiana', 'code_2_digit' => 'IN'),
		array('name' => 'Iowa', 'code_2_digit' => 'IA'),
		array('name' => 'Kansas', 'code_2_digit' => 'KS'),
		array('name' => 'Kentucky', 'code_2_digit' => 'KY'),
		array('name' => 'Louisiana', 'code_2_digit' => 'LA'),
		array('name' => 'Maine', 'code_2_digit' => 'ME'),
		array('name' => 'Maryland', 'code_2_digit' => 'MD'),
		array('name' => 'Massachusetts', 'code_2_digit' => 'MA'),
		array('name' => 'Michigan', 'code_2_digit' => 'MI'),
		array('name' => 'Minnesota', 'code_2_digit' => 'MN'),
		array('name' => 'Mississippi', 'code_2_digit' => 'MS'),
		array('name' => 'Missouri', 'code_2_digit' => 'MO'),
		array('name' => 'Montana', 'code_2_digit' => 'MT'),
		array('name' => 'Nebraska', 'code_2_digit' => 'NE'),
		array('name' => 'Nevada', 'code_2_digit' => 'NV'),
		array('name' => 'New Hampshire', 'code_2_digit' => 'NH'),
		array('name' => 'New Jersey', 'code_2_digit' => 'NJ'),
		array('name' => 'New Mexico', 'code_2_digit' => 'NM'),
		array('name' => 'New York', 'code_2_digit' => 'NY'),
		array('name' => 'North Carolina', 'code_2_digit' => 'NC'),
		array('name' => 'North Dakota', 'code_2_digit' => 'ND'),
		array('name' => 'Ohio', 'code_2_digit' => 'OH'),
		array('name' => 'Oklahoma', 'code_2_digit' => 'OK'),
		array('name' => 'Oregon', 'code_2_digit' => 'OR'),
		array('name' => 'Pennsylvania', 'code_2_digit' => 'PA'),
		array('name' => 'Puerto Rico', 'code_2_digit' => 'PR'),
		array('name' => 'Rhode Island', 'code_2_digit' => 'RI'),
		array('name' => 'South Carolina', 'code_2_digit' => 'SC'),
		array('name' => 'South Dakota', 'code_2_digit' => 'SD'),
		array('name' => 'Tennessee', 'code_2_digit' => 'TN'),
		array('name' => 'Texas', 'code_2_digit' => 'TX'),
		array('name' => 'Utah', 'code_2_digit' => 'UT'),
		array('name' => 'Vermont', 'code_2_digit' => 'VT'),
		array('name' => 'Virginia', 'code_2_digit' => 'VA'),
		array('name' => 'Washington', 'code_2_digit' => 'WA'),
		array('name' => 'West Virginia', 'code_2_digit' => 'WV'),
		array('name' => 'Wisconsin', 'code_2_digit' => 'WI'),
		array('name' => 'Wyoming', 'code_2_digit' => 'WY'),
	),

	'canada_provinces' => array(
		array('name' => 'Alberta', 'code_2_digit' => 'AB'),
		array('name' => 'British Columbia', 'code_2_digit' => 'BC'),
		array('name' => 'Manitoba', 'code_2_digit' => 'MB'),
		array('name' => 'New Brunswick', 'code_2_digit' => 'NB'),
		array('name' => 'Newfoundland', 'code_2_digit' => 'NF'),
		array('name' => 'Northwest Territories', 'code_2_digit' => 'NT'),
		array('name' => 'Nova Scotia', 'code_2_digit' => 'NS'),
		array('name' => 'Nunavut', 'code_2_digit' => 'NU'),
		array('name' => 'Ontario', 'code_2_digit' => 'ON'),
		array('name' => 'Prince Edward Island', 'code_2_digit' => 'PE'),
		array('name' => 'Quebec', 'code_2_digit' => 'PQ'),
		array('name' => 'Saskatchewan', 'code_2_digit' => 'SK'),
		array('name' => 'Yukon', 'code_2_digit' => 'YT'),
	),

	'mexico_states' => array(
		array('name' => 'Aguascalientes', 'code_2_digit' => 'AG'),
		array('name' => 'Baja California', 'code_2_digit' => 'BJ'),
		array('name' => 'Baja California Sur', 'code_2_digit' => 'BS'),
		array('name' => 'Campeche', 'code_2_digit' => 'CP'),
		array('name' => 'Chiapas', 'code_2_digit' => 'CH'),
		array('name' => 'Chihuahua', 'code_2_digit' => 'CI'),
		array('name' => 'Coahuila de Zaragoza', 'code_2_digit' => 'CU'),
		array('name' => 'Colima', 'code_2_digit' => 'CL'),
		array('name' => 'Distrito Federal', 'code_2_digit' => 'DF'),
		array('name' => 'Durango', 'code_2_digit' => 'DG'),
		array('name' => 'Estado Mexico', 'code_2_digit' => 'EM'),
		array('name' => 'Guanajuato', 'code_2_digit' => 'GJ'),
		array('name' => 'Guerrero', 'code_2_digit' => 'GR'),
		array('name' => 'Hidalgo', 'code_2_digit' => 'HG'),
		array('name' => 'Jalisco', 'code_2_digit' => 'JA'),
		array('name' => 'Mexico', 'code_2_digit' => 'MX'),
		array('name' => 'Michoacan', 'code_2_digit' => 'MH'),
		array('name' => 'Morelos', 'code_2_digit' => 'MR'),
		array('name' => 'Nayarit', 'code_2_digit' => 'NA'),
		array('name' => 'Nuevo Leon', 'code_2_digit' => 'NL'),
		array('name' => 'Oaxaca', 'code_2_digit' => 'OA'),
		array('name' => 'Puebla', 'code_2_digit' => 'PU'),
		array('name' => 'Queretaro', 'code_2_digit' => 'QA'),
		array('name' => 'Quintana Roo', 'code_2_digit' => 'QR'),
		array('name' => 'San Luis Potosi', 'code_2_digit' => 'SL'),
		array('name' => 'Sinaloa', 'code_2_digit' => 'SI'),
		array('name' => 'Sonora', 'code_2_digit' => 'SO'),
		array('name' => 'Tabasco', 'code_2_digit' => 'TA'),
		array('name' => 'Tamaulipas', 'code_2_digit' => 'TM'),
		array('name' => 'Tlaxcala', 'code_2_digit' => 'TL'),
		array('name' => 'Veracruz Llave', 'code_2_digit' => 'VL'),
		array('name' => 'Yucatan', 'code_2_digit' => 'YC'),
		array('name' => 'Zacatecas', 'code_2_digit' => 'ZT'),
	),

	'brazil_states' => array(
		array('name' => 'Acre', 'code_2_digit' => 'AC'),
		array('name' => 'Alagoas', 'code_2_digit' => 'AL'),
		array('name' => 'Amapa', 'code_2_digit' => 'AP'),
		array('name' => 'Amazonas', 'code_2_digit' => 'AM'),
		array('name' => 'Bahia', 'code_2_digit' => 'BA'),
		array('name' => 'Ceara', 'code_2_digit' => 'CE'),
		array('name' => 'Distrito Federal', 'code_2_digit' => 'DF'),
		array('name' => 'Espirito Santo', 'code_2_digit' => 'ES'),
		array('name' => 'Goias', 'code_2_digit' => 'GO'),
		array('name' => 'Maranhao', 'code_2_digit' => 'MA'),
		array('name' => 'Mato Grosso', 'code_2_digit' => 'MT'),
		array('name' => 'Mato Grosso do Sul', 'code_2_digit' => 'MS'),
		array('name' => 'Minas Gerais', 'code_2_digit' => 'MG'),
		array('name' => 'Para', 'code_2_digit' => 'PA'),
		array('name' => 'Paraiba', 'code_2_digit' => 'PB'),
		array('name' => 'Parana', 'code_2_digit' => 'PR'),
		array('name' => 'Pernambuco', 'code_2_digit' => 'PE'),
		array('name' => 'Piaui', 'code_2_digit' => 'PI'),
		array('name' => 'Rio Grande do Norte', 'code_2_digit' => 'RN'),
		array('name' => 'Rio Grande do Sul', 'code_2_digit' => 'RS'),
		array('name' => 'Rio de Janeiro', 'code_2_digit' => 'RJ'),
		array('name' => 'Rondonia', 'code_2_digit' => 'RO'),
		array('name' => 'Roraima', 'code_2_digit' => 'RR'),
		array('name' => 'Santa Catarina', 'code_2_digit' => 'SC'),
		array('name' => 'Sao Paulo', 'code_2_digit' => 'SP'),
		array('name' => 'Sergipe', 'code_2_digit' => 'SE'),
		array('name' => 'Tocantins', 'code_2_digit' => 'TO'),
	),

	'australia_states' => array(
		array('name' => 'Australian Capital Territory', 'code_2_digit' => 'CT'),
		array('name' => 'New South Wales', 'code_2_digit' => 'NS'),
		array('name' => 'Northern Territory', 'code_2_digit' => 'NT'),
		array('name' => 'Queensland', 'code_2_digit' => 'QL'),
		array('name' => 'South Australia', 'code_2_digit' => 'SA'),
		array('name' => 'Tasmania', 'code_2_digit' => 'TS'),
		array('name' => 'Victoria', 'code_2_digit' => 'VI'),
		array('name' => 'Western Australia', 'code_2_digit' => 'WA'),
	),

);